# dubbo 配置项，对应 DubboConfigurationProperties 配置类
dubbo:
  # Dubbo 应用配置
  application:
    name: user-service-provider # 应用名
  # Dubbo 注册中心配
  registry:
    address: zookeeper://127.0.0.1:2181 # 注册中心地址。个鞥多注册中心，可见 http://dubbo.apache.org/zh-cn/docs/user/references/registry/introduction.html 文档。
    client: curator
  # Dubbo 服务提供者协议配置
  protocol:
    port: 20001 # 协议端口。使用 -1 表示随机端口。
    name: dubbo # 使用 `dubbo://` 协议。更多协议，可见 http://dubbo.apache.org/zh-cn/docs/user/references/protocol/introduction.html 文档
  # Dubbo 服务提供者配置

  provider:
    timeout: 1000 # 【重要】远程服务调用超时时间，单位：毫秒。默认为 1000 毫秒，胖友可以根据自己业务修改
    filter: -exception # 去掉 ExceptionFilter
    UserRpcService:
      version: 1.0.0


spring:
  application:
    name: user-service-provider
  # 对应 RedisProperties 类
  redis:
    host: 127.0.0.1
    port: 6379
    password: # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。

#redis二级缓存在此配置
levelcache:
  #  namespace: zrk # redis 频道与 messageList 标识相关，默认使用 spring.application.name。
  defaultExpire: 50 #二级缓存默认的 expire 时间为 50s。
  cachesExpire:
    users: 80 #缓存 users 下所有 key 的 expire 为 80s。
  preLoadTime: 20 # 当 redis 二级缓存key命中，若 expire 在 20s 以下则主动刷新。

#logging:
#  level:
#    cn:
#      zhouruikang:
#        debug

#    # 日志文件配置
#  file:
#    #    path: /Users/ruikangzhou/logs/ # 日志文件路径。
#    name: //Users/ruikangzhou/Desktop/logs/${spring.application.name}.log # 日志文件名。
#    max-history: 7 # 日志文件要保留的归档的最大天数。默认为 7 天。
#    max-size: 10MB # 日志文件的最大大小。默认为 10MB 。
